# Please adjust to your needs (see https://www.gitpod.io/docs/config-gitpod-file)
# and commit this file to your remote git repository to share the goodness with others.

image:
  file: .gitpod.Dockerfile

ports:
  - port: 3001
    onOpen: open-browser

tasks:
  - before: bash .gp/bash/before-tasks.sh
    init: |
      npm install npm pm2 -g && npm run setup && pm2 install pm2-logrotate
    name: Main Terminal
  - openMode: split-right
    command: |
      pm2 start server/server.js --name uptime-kuma
    name: Kuma Server

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
